# Introduction 

Justice system is expected to be free and fair. However, there are specific cases where gender bias is witnessed. Favoring a specific gender for whatever reason leads to wrong sentencing and a rot in the justice system. This study examines the relationship between male and female prison population. Specifically, the study aims to find out which specific gender dominates the prisons. 

The study uses the prison data available on GitHu:https://raw.githubusercontent.com/vera-institute/incarceration-trends/master/incarceration_trends.csv. The data contains a combined of 121 vars However, this study uses only 6 vars The vars of interest include county, male adult prisoners, female adult prisoners, combined prison population . The vars were chosen because they are relevant to the objective of the report. The vars contain the info necessary to compare the trends in the number of male and female convicts and determine whether there exists favoritism in the justice system.

In addition to sampling the vars of interest, data preparation also involved removing all the rows with missing data. The summary statics results reveal that there were states with 0 males or o females in prison (min = 0). The max number of males in prison was 12633, while the max number of adult females in prison was 1302. The average number of adult males in prison was 750 while the average number of adult females in prison was 109. The min number of combined population in prison was 730 while the max number of combined adult population in prison was 8398739.

# Importing data

data<-read.csv('https://raw.githubusercontent.com/vera-institute/incarceration-trends/master/incarceration_trends.csv')




names(data)


head(data)


data<-data %>% drop_na()



head(data)


Fips<-data$fips
Year<-data$year
State<-data$state
County<-data$county_name
Males<-data$male_adult_prison_pop
Female<-data$female_adult_prison_pop
combined_pop<-data$combined_pop
prisonData<-data.frame(Fips,Year,State,County,Males,Female,combined_pop)
head(prisonData)



summary(prisonData)



# Trend Plots Over Time (Year)

*1. Chart showing trends of time for the combined prison population*

ggplot(data = prisonData)+
  geom_smooth(aes(x=Year,y=combined_pop))+
  labs(title = "Line plot showing trends combined prison population over Time"
       ,x="Time (Years)",y="combined prison Population")


*2. Chart showing trends of time for the male prison population*

ggplot(data = prisonData)+
  geom_smooth(aes(x=Year,y=Males))+
  labs(title = "Line plot showing trends male prison population over Time"
       ,x="Time (Years)",y="Male prison Population")


*3. Chart showing trends of time for the female prison population*

ggplot(data = prisonData)+
  geom_smooth(aes(x=Year,y=Female))+
  labs(title = "Line plot showing trends female prison population over Time"
       ,x="Time (Years)",y="Female prison Population")



# 2 A Chart comparing tow vars: Male prison population vs female prison populaiton 

ggplot(data = prisonData)+
  geom_point(aes(x=Female,y=Males))+
  labs(title = "Scatter plot showing relationship between male 
                          and female prison populations"
       ,x="Female Population",y="Male Populaion")


# A map showing how the male populaitons vary by state

plot_usmap(regions = "counties",col='blue') + 
  labs(title = "Male prisons by counties",
       subtitle = "A map showing how the male populaitons vary by Counties") + 
  theme(panel.background=element_blank())


# Summary 
In essence, the combined prison population was steadily decreasing over time. Earlier periods had higher combined prison population than later periods.
Also, both prison populations were steadily decreasing over time. The results suggest that the crime rates decreased over time. In addition, the results could also suggest that there was a general change in behavior in the country, and a change in the justice system.

The scatter plot of male prison population against female prison population indicates that there exists a strong positive correlation/relationship between male prison population and female prison population. The relationship implies that the male and female population increase and decrease together.

The southern states of the United States had higher number of adult males in prison than the northern states.
